name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -f docker/frankenphp/Dockerfile.frankenphp -t admin-api .

      - name: Install Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && composer install --no-interaction"

      - name: Code Style Check
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && ./vendor/bin/phpcs --parallel=1"

      - name: Static Analysis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && ./vendor/bin/phpstan analyse --memory-limit=1G --no-progress"

      - name: Security Check
        uses: symfonycorp/security-checker-action@v5