name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -f docker/frankenphp/Dockerfile.frankenphp -t admin-api .

      - name: Install Dependencies
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && composer install --no-interaction"

      - name: Run Database Migrations
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && ./vendor/bin/phinx migrate -e testing"

      - name: Run Tests
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && ./vendor/bin/phpunit --colors=always --testsuite=all"

      - name: Upload Coverage Report
        if: success()
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/app \
            asset-server \
            sh -c "git config --global --add safe.directory /app && ./vendor/bin/phpunit --coverage-clover clover.xml"